# Generated by Django 4.0.1 on 2022-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registered_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
