# Generated by Django 4.0.2 on 2022-02-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registered_user',
        ),
    ]
